spring.application.name=backend

# Database properties (H2 In-Memory for development without MySQL)
spring.datasource.url=jdbc:h2:file:./data/campus_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 Web Console to view database at /h2-console
spring.h2.console.enabled=true

# Server port configs
server.port=8080
