spring.application.name=backend

# Database properties
spring.datasource.url=jdbc:mysql://localhost:3306/campus_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# Hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port configs
server.port=8080
