spring.application.name=Campus-Hub-Module4
spring.data.mongodb.uri=mongodb+srv://pasanpasan42:pasakolla123@cluster0.7yy3s.mongodb.net/campus_hub?retryWrites=true&w=majority
spring.data.mongodb.database=campus_hub

spring.security.oauth2.client.registration.google.client-id=617516582742-cmgbgv1k2lsjrrq6ei7qftjiuldm9tk9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

server.port=8081

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=http://localhost:5173,http://localhost:5174

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pasanpasan42@gmail.com
spring.mail.password=wsbplpkbzssdsrrr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
