spring.application.name=Campus-Hub-Module4
spring.data.mongodb.uri=mongodb://pasanpasan42:pasakolla123@cluster0-shard-00-00.7yy3s.mongodb.net:27017,cluster0-shard-00-01.7yy3s.mongodb.net:27017,cluster0-shard-00-02.7yy3s.mongodb.net:27017/?ssl=true&replicaSet=atlas-mlkt6u-shard-0&authSource=admin&appName=Cluster0&connectTimeoutMS=30000&socketTimeoutMS=30000
spring.data.mongodb.database=campus_hub

spring.security.oauth2.client.registration.google.client-id=617516582742-cmgbgv1k2lsjrrq6ei7qftjiuldm9tk9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

server.port=8081

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=http://localhost:5173
